In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import streamlit as st
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor
from sklearn.metrics import accuracy_score, mean_squared_error



df= pd.read_csv("ev_thermal_mixed_dataset.csv")
df

,time_s,ambient_temp,voltage_V,current_A,SOC_percent,coolant_flow,fan_speed,system_temp,overheat_risk
0,0.0,20.67,high,high,76.3,weak,medium,hot,1
1,NaN,34.11,3.589,high,low,weak,2804,42.8,1
2,120.0,NaN,4.084,medium,86.2,strong,medium,NaN,1
3,180.0,41.67,4.185,1.414,low,strong,fast,26.02,0
4,240.0,medium,4.003,1.028,NaN,1.32,NaN,warm,0
...,...,...,...,...,...,...,...,...,...
495,29700.0,NaN,3.622,2.196,86.4,weak,fast,28.41,0
496,29760.0,low,medium,1.438,62.6,weak,slow,NaN,1
497,29820.0,low,3.988,medium,92.0,NaN,2804,25.11,0
498,29880.0,27.89,3.52,1.454,49.5,1.32,fast,49.98,1
499,29940.0,29.96,4.163,medium,75.5,weak,2804,warm,0

In [59]:
df.tail()

,time_s,ambient_temp,voltage_V,current_A,SOC_percent,coolant_flow,fan_speed,system_temp,overheat_risk
495,29700.0,NaN,3.622,2.196,86.4,weak,fast,28.41,0
496,29760.0,low,medium,1.438,62.6,weak,slow,NaN,1
497,29820.0,low,3.988,medium,92.0,NaN,2804,25.11,0
498,29880.0,27.89,3.52,1.454,49.5,1.32,fast,49.98,1
499,29940.0,29.96,4.163,medium,75.5,weak,2804,warm,0

In [60]:
df.head()

,time_s,ambient_temp,voltage_V,current_A,SOC_percent,coolant_flow,fan_speed,system_temp,overheat_risk
0,0.0,20.67,high,high,76.3,weak,medium,hot,1
1,NaN,34.11,3.589,high,low,weak,2804,42.8,1
2,120.0,NaN,4.084,medium,86.2,strong,medium,NaN,1
3,180.0,41.67,4.185,1.414,low,strong,fast,26.02,0
4,240.0,medium,4.003,1.028,NaN,1.32,NaN,warm,0

In [61]:
df.dtypes

time_s           float64
ambient_temp      object
voltage_V         object
current_A         object
SOC_percent       object
coolant_flow      object
fan_speed         object
system_temp       object
overheat_risk      int64
dtype: object

In [62]:
df.isna().sum()

time_s           48
ambient_temp     43
voltage_V        43
current_A        46
SOC_percent      42
coolant_flow     49
fan_speed        46
system_temp      52
overheat_risk     0
dtype: int64

In [63]:
df.dtypes

time_s           float64
ambient_temp      object
voltage_V         object
current_A         object
SOC_percent       object
coolant_flow      object
fan_speed         object
system_temp       object
overheat_risk      int64
dtype: object

In [64]:
df.columns

Index(['time_s', 'ambient_temp', 'voltage_V', 'current_A', 'SOC_percent',
       'coolant_flow', 'fan_speed', 'system_temp', 'overheat_risk'],
      dtype='object')

In [65]:

df1 = ['time_s','ambient_temp','current_A','SOC_percent','system_temp']
for col in df1:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\4141998246.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\4141998246.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\4141998246.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\4141998246.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\4141998246.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [66]:
df2 = ['voltage_V','coolant_flow','fan_speed']
for col in df2:
    df[col] = df[col].astype(str)
    df[col].replace("nan", np.nan, inplace=True)
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace("nan", np.nan, inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace("nan", np.nan, inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace("nan", np.nan, inplace=True)
C:\Users\SHAJAHAN\AppData\Local\Temp\ipykernel_19072\2997593275.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder


encoder = OneHotEncoder(handle_unknown='ignore')
encoded = encoder.fit_transform(df[df2]).toarray()
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(df2))

In [68]:
df.dtypes

time_s           float64
ambient_temp     float64
voltage_V         object
current_A        float64
SOC_percent      float64
coolant_flow      object
fan_speed         object
system_temp      float64
overheat_risk      int64
dtype: object

In [69]:
df.isna().sum()

time_s           0
ambient_temp     0
voltage_V        0
current_A        0
SOC_percent      0
coolant_flow     0
fan_speed        0
system_temp      0
overheat_risk    0
dtype: int64

In [70]:
df

,time_s,ambient_temp,voltage_V,current_A,SOC_percent,coolant_flow,fan_speed,system_temp,overheat_risk
0,0.0,20.67,high,1.521,76.3,weak,medium,39.20,1
1,15210.0,34.11,3.589,1.521,59.2,weak,2804,42.80,1
2,120.0,31.60,4.084,1.521,86.2,strong,medium,39.20,1
3,180.0,41.67,4.185,1.414,59.2,strong,fast,26.02,0
4,240.0,31.60,4.003,1.028,59.2,1.32,2804,39.20,0
...,...,...,...,...,...,...,...,...,...
495,29700.0,31.60,3.622,2.196,86.4,weak,fast,28.41,0
496,29760.0,31.60,medium,1.438,62.6,weak,slow,39.20,1
497,29820.0,31.60,3.988,1.521,92.0,strong,2804,25.11,0
498,29880.0,27.89,3.52,1.454,49.5,1.32,fast,49.98,1
499,29940.0,29.96,4.163,1.521,75.5,weak,2804,39.20,0

In [71]:
df.dtypes

time_s           float64
ambient_temp     float64
voltage_V         object
current_A        float64
SOC_percent      float64
coolant_flow      object
fan_speed         object
system_temp      float64
overheat_risk      int64
dtype: object

In [72]:
df['system_temp']

0      39.20
1      42.80
2      39.20
3      26.02
4      39.20
       ...
495    28.41
496    39.20
497    25.11
498    49.98
499    39.20
Name: system_temp, Length: 500, dtype: float64

In [73]:
x = pd.concat([df[df1],encoded_df],  axis=1)
y_class = df['overheat_risk']
y_reg = df['system_temp']

In [74]:
scaler =StandardScaler()

x_scaled = scaler.fit_transform(x)

In [75]:
len(x)

500

In [76]:
from sklearn.model_selection import train_test_split

x_train_c, x_test_c, y_train_c, y_test_c = train_test_split(x_scaled, y_class, test_size=0.2, random_state=42)

clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(x_train_c, y_train_c)
y_pred_c = clf.predict(x_test_c)
print("Classification Accuracy:", accuracy_score(y_test_c, y_pred_c))

Classification Accuracy: 0.78

In [77]:

x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(x_scaled, y_reg, test_size=0.2, random_state=42)
reg = GradientBoostingRegressor(n_estimators=200, random_state=42)
reg.fit(x_train_r, y_train_r)
y_pred_r = reg.predict(x_test_r)
print("Regression RMSE:", np.sqrt(mean_squared_error(y_test_r, y_pred_r)))

Regression RMSE: 0.08201757946095127

In [78]:
def control_strategy(pred_temp, pred_risk):
    safe_min, safe_max = 25, 45 
    
    if pred_temp > safe_max or pred_risk == 1:
        return {"coolant_flow":"strong", "fan_speed":"fast", "heating":"off"}
    elif pred_temp < safe_min:
        return {"coolant_flow":"weak", "fan_speed":"slow", "heating":"on"}
    else:
        return {"coolant_flow":"normal", "fan_speed":"medium", "heating":"off"}

In [79]:

sample_idx = 5
sample_features = x_scaled[sample_idx].reshape(1,-1)
pred_risk = clf.predict(sample_features)[0]
pred_temp = reg.predict(sample_features)[0]

decision = control_strategy(pred_temp, pred_risk)
print(f"Predicted Temp: {pred_temp:.2f}, Risk: {pred_risk}, Decision: {decision}")

Predicted Temp: 42.90, Risk: 1, Decision: {'coolant_flow': 'strong', 'fan_speed': 'fast', 'heating': 'off'}

In [ ]:
import joblib


joblib.dump(clf, "classifier.pkl")
joblib.dump(reg, "regressor.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoder, "encoder.pkl")

['encoder.pkl']